title: SandwichHub
author: yobaus
email: p_baus@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A blog All about sandwichs 

# social links
twitter_username: yobaus
github_username:  yobaus

theme: jekyll-theme-minimal
show_excerpts: true # set to false to remove excerpts on the homepage
